import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider
} from "@apollo/client";
import Link from 'next/link'

import styles from '../styles/Home.module.css';
import { Feed } from './components/feed/feed';
import { SignalProvider } from './provider/signal';

const client = new ApolloClient({
  uri: 'http://localhost:4000/graphql',
  cache: new InMemoryCache()
});

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <SignalProvider>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div>
              <Feed />
              <p>
                Read{' '}
                <Link href="/about">about page!</Link>
              </p>
              <p>
                <Link href="/hacker-news">Hacker News top stories
                </Link>
              </p>
              <p>
                <Link href="/kitchen-sink">Kitchen sink</Link>
              </p>
            </div>
          </main>

          <footer className={styles.footer}>
            <p>Example SDUI application</p>
          </footer>
        </div>
      </SignalProvider>
    </ApolloProvider>
  )
}

export default Home
